### PR TITLE
Bug 1 in findDeliveryCommand

### LINKED ISSUE #156: Bug 1 in findDeliveryCommand
Location: int numDeliveriesFound = model.getFilteredPersonList().size(); //line 43
Problem: Use getFilteredDeliveryList() instead.
Unintended side-effect: When no delivery is found, the intended error message is "Error: No delivery found.". However, given that we use getFilteredPersonList() instead, the message says "0 deliveries found!" instead. This is because we are always checking the size of the filteredDeliveryList directly instead of reusing numDeliveriesFound at line 49, as long as numDeliveriesFound != 0.

### PR DESCRIPTION
**Pull request by wucx-0**
fix #156

### CODE REVIEW

File: src/main/java/seedu/foodbook/logic/commands/FindDeliveryCommand.java [hunk 1]
```diff
@@ -36,14 +37,14 @@ public FindDeliveryCommand(DeliveryPredicate predicate) {
...
+    public CommandResult execute(Model model) throws CommandException {
         requireNonNull(model);
         model.updateFilteredDeliveryList(predicate);
 
-        int numDeliveriesFound = model.getFilteredPersonList().size();
+        int numDeliveriesFound = model.getFilteredDeliveryList().size();
 
         if (numDeliveriesFound == 0) {
-            return new CommandResult(MESSAGE_NO_DELIVERY_FOUND, CommandResult.UiPanel.DELIVERIES);
+            throw new CommandException(MESSAGE_NO_DELIVERY_FOUND);
```
Comment (Nsohko) [inline src/main/java/seedu/foodbook/logic/commands/FindDeliveryCommand.java]: Why does this return an error?

find_client returns the command result

**Review by Nsohko — CHANGES_REQUESTED** [review]

**Review by Nsohko — APPROVED** [review]
